server:
  port: 10010

spring:
  application:
    name: gateway # 服务器名称
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址注册中心
    gateway:
      routes: # 加s的代表可以有多个，数组形式
        - id: user-server # 路由唯一标识，必须是唯一的
          uri: lb://userserver # 路由的目标地址
          predicates: # 路由断言，判断是否有符合规则，可以配置多个
            - Path=/user/** # 路径断言，判断是否是以/user开头的，如果是则符合规则
        - id: order-server
          uri: lb://orderserver
          predicates:
            - Path=/order/**
      default-filters: # 默认过滤项
        - AddRequestHeader=Truth, zcl is freaking awesome!

