server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:13306/cloud_order?useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  #  微服务名称
  application:
    name: orderserver
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos服务地址
      discovery:
        cluster-name:  HZ # 集群名称
    sentinel:
      transport:
        dashboard: localhost:8090
      web-context-unify: false # 关闭context整合
#        namespace: 8656bcbd-8886-4032-9ca6-cb89e58ea69d # 命名空间的id
#        ephemeral: false # 改为非临时实例，nacos主动发起请求实例是否健康

mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

#eureka:
#  client:
#    service-url: # 配置eureka地址
#      defaultZone: http://127.0.0.1:10086/eureka

# 负载均衡
userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则


# 开启饥饿加载
ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients: userserver # 开启饥饿加载的服务名称，是一个集合,一个可以直接写，两个通过 - userserver拼接

# 配置feign的配置日志
#feign:
#  client:
#    config:
#      default: # 这里用default就是全局配置，如果是写服务名称，则是针对某个微服务的配置
#        loggerLevel: FULL #  日志级别

# 替换底层的实现
feign:
  httpclient:
    enabled: true # 支持httpclient的开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数据
  sentinel:
    enabled: true # 开启feign对sentin的支持


